// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfDm_GLiW0t43qhqqm7RvMPMVSvYMWuWs',
    appId: '1:76479788336:web:835ecb5d6e635d603384f5',
    messagingSenderId: '76479788336',
    projectId: 'fireflutter-49b6a',
    authDomain: 'fireflutter-49b6a.firebaseapp.com',
    storageBucket: 'fireflutter-49b6a.appspot.com',
    measurementId: 'G-L0XG923D1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtOTwLEVYWR_TnA1sPHGt0dpOlmCnjC24',
    appId: '1:76479788336:android:4bb5d6f96608de533384f5',
    messagingSenderId: '76479788336',
    projectId: 'fireflutter-49b6a',
    storageBucket: 'fireflutter-49b6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCevamLXBhfLxzU-FgdMNlalV76FB16yR4',
    appId: '1:76479788336:ios:93ad289b7d4b95433384f5',
    messagingSenderId: '76479788336',
    projectId: 'fireflutter-49b6a',
    storageBucket: 'fireflutter-49b6a.appspot.com',
    iosClientId: '76479788336-3hejkijd9nh94thq91u63n84rur2rogl.apps.googleusercontent.com',
    iosBundleId: 'com.example.latihanWarung',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCevamLXBhfLxzU-FgdMNlalV76FB16yR4',
    appId: '1:76479788336:ios:93ad289b7d4b95433384f5',
    messagingSenderId: '76479788336',
    projectId: 'fireflutter-49b6a',
    storageBucket: 'fireflutter-49b6a.appspot.com',
    iosClientId: '76479788336-3hejkijd9nh94thq91u63n84rur2rogl.apps.googleusercontent.com',
    iosBundleId: 'com.example.latihanWarung',
  );
}
